### ISSUE TITLE
Import error after running setup.py

### ISSUE THREAD

**Issue by petrvanblokland** [LettError/filibuster#3]
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import filibuster
>>> from filibuster import content
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name content
>>>

**Comment by LettError** [comment]
Which file?

**Comment by petrvanblokland** [comment]
Just importing filibuster in terminal Python.

+++ python setyp.py install
+++ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import filibuster
>>> from filibuster import content
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name content

**Comment by LettError** [comment]
This works:
```
eBookPro:filibuster erik$ sudo python setup.py develop
Password:
running develop
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running egg_info
writing Lib/Filibuster.egg-info/PKG-INFO
writing top-level names to Lib/Filibuster.egg-info/top_level.txt
writing dependency_links to Lib/Filibuster.egg-info/dependency_links.txt
reading manifest file 'Lib/Filibuster.egg-info/SOURCES.txt'
writing manifest file 'Lib/Filibuster.egg-info/SOURCES.txt'
running build_ext
Creating /Library/Python/2.7/site-packages/Filibuster.egg-link (link to Lib)
Filibuster 2 is already the active version in easy-install.pth

Installed /Users/erik/code/filibuster/Lib
Processing dependencies for Filibuster==2
Finished processing dependencies for Filibuster==2
```

**Comment by petrvanblokland** [comment]
Works here too, and so does install. 
But if you go into python, then do
from filibuster import content 
what does it say?
